<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\PlatformServiceTemplate.Domain\PlatformServiceTemplate.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>PlatformServiceTemplate.Application</RootNamespace>
  </PropertyGroup>
</Project>
